
name: Print Inputs

on:
  workflow_run:
    workflows: ["Hello World"]
    types:
      - completed

jobs:
  printing_star:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Message
        run: echo "***************************Hello****************************"
        
  printing_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Inputs
        run: echo " ${{ CALLER }} "
