
name: Print Inputs

on:
  workflow_run:
    workflows: ["Hello World"]
    types:
      - completed

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Input Printing
        run: echo "***************************Hello****************************"
