name: Hello World

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, world!"
        
  invoking-helper:
    uses: JITU960/file-comparator/.github/workflows/input_accepting_workflow.yml@master
    
